name: Hello World

# Events 
on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

# Workflow / Jobs 
jobs: 
  hello1: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Hello1
        run: echo "Hello World 1" 
        shell: bash 
  hello2: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4
      - name: Hello2
        run: echo "Hello World 2" 
        shell: bash 
